apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-hshan-setting
spec:
  forms:
    - group: general
      label: 基本设置
      formSchema:
        - $formkit: text
          name: home_title
          label: 首页展示博客名
          placeholder: 用于首页展示名字
          help: 注意：如填写，会覆盖原有博客名
        - $formkit: text
          name: home_description
          label: 首页描述
          placeholder: 用于首页描述
        - $formkit: color
          name: base_color
          label: 网站主题色
          placeholder: 网站主题色
          value: "#2474b5"
        - $formkit: text
          name: home_cover
          label: 首页背景
        - $formkit: radio
          name: enabled_index_cover_height
          label: 首页开启全屏图片
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: text
          name: header_logoimg
          label: 菜单 Logo
        - $formkit: text
          name: header_logo_height
          label: 菜单 Logo 高度
          placeholder: 30px
        - $formkit: radio
          name: post_list_style
          label: 首页文章风格
          value: standard
          options:
            - value: standard
              label: 标准
            - value: simple
              label: 简单
            - value: card
              label: 卡片
        - $formkit: radio
          name: card_random_cover
          label: 卡片文章风格随机选择封面
          value: false
          help: "即使开启了此选项,也只有文章没有封面的情况下才会生效.请查看教程:
            https://baozi.fun/archives/random-thumbnail"
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: card_random_cover_img_suffix
          label: 卡片文章风格随机选择封面后缀
          value: png
          help: 随机封面后缀
          options:
            - value: png
              label: png
            - value: jpeg
              label: jpeg
            - value: jpg
              label: jpg
        - $formkit: number
          name: card_random_cover_img_num
          label: 卡片文章风格随机选择封面数量
          value: 4
        - $formkit: radio
          name: auto_night_mode
          label: 暗夜模式总开关
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: night_mode
          label: 暗夜模式顶部按钮(需要先打开暗黑模式总开关)
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: text
          name: night_mode_start_time
          label: 暗夜模式开始时间
          placeholder: 暗夜模式开始时间 默认18
          help: 注意：24小时制的小时. 比如:18
        - $formkit: text
          name: night_mode_end_time
          label: 暗夜模式结束时间
          placeholder: 暗夜模式结束时间,  默认6
          help: 注意：24小时制的小时. 比如:6
        - $formkit: radio
          name: top_search
          label: 搜索
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: post_summary
          label: 首页文章摘要
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: custom_scroller
          label: 自定义滚动条
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: color
          name: custom_scroller_color
          label: 自定义滚动条颜色
          placeholder: 网站主题色
          value: "#2474b5"
        - $formkit: text
          name: Icp
          label: ICP 备案号
          placeholder: "填入 ICP 备案号，没有则不填. "
        - $formkit: text
          name: PublicSecurityRecord
          label: 网安备案号
          placeholder: 填入网安备案号代码，没有则不填
        - $formkit: text
          name: QR_code_zfb
          label: 支付宝二维码链接
          placeholder:
        - $formkit: text
          name: QR_code_wx
          label: 微信二维码链接
          placeholder: 微信收款二维码链接，不填不显示
    - group: head_img
      label: 网页首部图片
      formSchema:
        - $formkit: text
          name: archives_patternimg
          label: 归档页面头部装饰图
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
        - $formkit: text
          name: links_patternimg
          label: 友情链接页面头部装饰图
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
        - $formkit: text
          name: tag_patternimg
          label: 标签页面头部装饰图
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
        - $formkit: text
          name: categories_patternimg
          label: 分类页面头部装饰图
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
        - $formkit: text
          name: journals_patternimg
          label: 日志下文章页面头部装饰图
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
        - $formkit: text
          name: photos_patternimg
          label: 相册页面头部装饰图
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
        - $formkit: text
          name: links_placeholder
          label: 友情链接默认用户头像
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
        - $formkit: text
          name: search_patternimg
          label: 搜索页面默认用户头像
          value: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    - group: post
      label: 文章页
      formSchema:
        - $formkit: radio
          name: post_toc
          label: 目录
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: post_nepre
          label: 下一篇
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: open_read_progress
          label: 是否使用阅读进度条
          value: true
          options:
            - value: true
              label: 显示
            - value: false
              label: 关闭
        - $formkit: color
          name: progress_color
          label: 阅读进度条颜色
          placeholder: 阅读进度条颜色
          value: "#2474b5"
        - $formkit: text
          name: post_max_wdth
          label: 文章最大宽度
          placeholder: "文章最大宽度, 比如: 800px"
          value: 800px
        - $formkit: text
          name: content_font_size
          label: 文章正文字体大小
          placeholder: "文章正文字体大小, 比如: 1.16rem 或 14px"
          value: 1.12rem
        - $formkit: text
          name: content_line_height
          label: 文章正文高度
          placeholder: "文章正文高度, 比如: 2rem 或 14px"
          value: 2rem
        - $formkit: radio
          name: enabled_visual_height
          label: 文章页开启全屏图片
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: social_share
          label: 开启文章分享
          value: false
          options:
            - value: true
              label: 是
            - value: false
              label: 否
        - $formkit: text
          name: share_disabeld
          label: 分享禁用
          placeholder: 文章分享禁用社交软件
          value: google,twitter,facebook
          help: "文章分享禁用社交软件,比如:
            google,twitter,facebook,weibo,qq,tencent,qzone,linkedin,wechat,doub\
            an,diandian"
        - $formkit: radio
          name: enabled_katex
          label: Katex 渲染
          value: false
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: radio
          name: copyright_clean
          label: 简洁版权信息
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
        - $formkit: textarea
          name: highlight_extra_languages
          label: 文章代码高亮语言
          help: 默认已经包含：<code>php,diff,java,css,bash,json,perl,swift,plaintext,ruby,yaml,sql,vbnet,ini,scss,less,cpp,typescript,csharp,rust,python,python-repl,objectivec,r,shell,makefile,go,xml,markdown,lua,javascript,php-template,kotlin,c</code><br>如果需要添加其他语言，请按照相同格式添加。
        - $formkit: select
          name: highlight_style
          label: 文章代码高亮主题
          value: default.min.css
          options:
            - value: a11y-dark.min.css
              label: a11y-dark.min.css
            - value: a11y-light.min.css
              label: a11y-light.min.css
            - value: agate.min.css
              label: agate.min.css
            - value: an-old-hope.min.css
              label: an-old-hope.min.css
            - value: androidstudio.min.css
              label: androidstudio.min.css
            - value: arduino-light.min.css
              label: arduino-light.min.css
            - value: arta.min.css
              label: arta.min.css
            - value: ascetic.min.css
              label: ascetic.min.css
            - value: atom-one-dark-reasonable.min.css
              label: atom-one-dark-reasonable.min.css
            - value: atom-one-dark.min.css
              label: atom-one-dark.min.css
            - value: atom-one-light.min.css
              label: atom-one-light.min.css
            - value: brown-paper.min.css
              label: brown-paper.min.css
            - value: codepen-embed.min.css
              label: codepen-embed.min.css
            - value: color-brewer.min.css
              label: color-brewer.min.css
            - value: dark.min.css
              label: dark.min.css
            - value: default.min.css
              label: default.min.css
            - value: devibeans.min.css
              label: devibeans.min.css
            - value: docco.min.css
              label: docco.min.css
            - value: far.min.css
              label: far.min.css
            - value: felipec.min.css
              label: felipec.min.css
            - value: foundation.min.css
              label: foundation.min.css
            - value: github-dark-dimmed.min.css
              label: github-dark-dimmed.min.css
            - value: github-dark.min.css
              label: github-dark.min.css
            - value: github.min.css
              label: github.min.css
            - value: gml.min.css
              label: gml.min.css
            - value: googlecode.min.css
              label: googlecode.min.css
            - value: gradient-dark.min.css
              label: gradient-dark.min.css
            - value: gradient-light.min.css
              label: gradient-light.min.css
            - value: grayscale.min.css
              label: grayscale.min.css
            - value: hybrid.min.css
              label: hybrid.min.css
            - value: idea.min.css
              label: idea.min.css
            - value: intellij-light.min.css
              label: intellij-light.min.css
            - value: ir-black.min.css
              label: ir-black.min.css
            - value: isbl-editor-dark.min.css
              label: isbl-editor-dark.min.css
            - value: isbl-editor-light.min.css
              label: isbl-editor-light.min.css
            - value: kimbie-dark.min.css
              label: kimbie-dark.min.css
            - value: kimbie-light.min.css
              label: kimbie-light.min.css
            - value: lightfair.min.css
              label: lightfair.min.css
            - value: lioshi.min.css
              label: lioshi.min.css
            - value: magula.min.css
              label: magula.min.css
            - value: mono-blue.min.css
              label: mono-blue.min.css
            - value: monokai-sublime.min.css
              label: monokai-sublime.min.css
            - value: monokai.min.css
              label: monokai.min.css
            - value: night-owl.min.css
              label: night-owl.min.css
            - value: nnfx-dark.min.css
              label: nnfx-dark.min.css
            - value: nnfx-light.min.css
              label: nnfx-light.min.css
            - value: nord.min.css
              label: nord.min.css
            - value: obsidian.min.css
              label: obsidian.min.css
            - value: paraiso-dark.min.css
              label: paraiso-dark.min.css
            - value: paraiso-light.min.css
              label: paraiso-light.min.css
            - value: pojoaque.min.css
              label: pojoaque.min.css
            - value: purebasic.min.css
              label: purebasic.min.css
            - value: qtcreator-dark.min.css
              label: qtcreator-dark.min.css
            - value: qtcreator-light.min.css
              label: qtcreator-light.min.css
            - value: rainbow.min.css
              label: rainbow.min.css
            - value: routeros.min.css
              label: routeros.min.css
            - value: school-book.min.css
              label: school-book.min.css
            - value: shades-of-purple.min.css
              label: shades-of-purple.min.css
            - value: srcery.min.css
              label: srcery.min.css
            - value: stackoverflow-dark.min.css
              label: stackoverflow-dark.min.css
            - value: stackoverflow-light.min.css
              label: stackoverflow-light.min.css
            - value: sunburst.min.css
              label: sunburst.min.css
            - value: tokyo-night-dark.min.css
              label: tokyo-night-dark.min.css
            - value: tokyo-night-light.min.css
              label: tokyo-night-light.min.css
            - value: tomorrow-night-blue.min.css
              label: tomorrow-night-blue.min.css
            - value: tomorrow-night-bright.min.css
              label: tomorrow-night-bright.min.css
            - value: vs.min.css
              label: vs.min.css
            - value: vs2015.min.css
              label: vs2015.min.css
            - value: xcode.min.css
              label: xcode.min.css
            - value: xt256.min.css
              label: xt256.min.css
    - group: custom
      label: 自定义
      formSchema:
        - $formkit: text
          name: TimeStatistics
          label: 站点运行时间统计
          help: 填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00
    - group: title
      label: 页面标题
      formSchema:
        - $formkit: text
          name: links_title
          label: 友链页面标题
          value: 友链
        - $formkit: text
          name: jounarls_title
          label: 日志页面标题
          value: 日志
        - $formkit: text
          name: tags_title
          label: 标签页面标题
          value: 标签列表
        - $formkit: text
          name: categories_title
          label: 分类列表页面标题
          value: 分类列表
        - $formkit: text
          name: achieve_title
          label: 归档页面标题
          value: 归档
        - $formkit: text
          name: photos_title
          label: 相册页面标题
          value: 相册
    - group: social
      label: 社交网络
      formSchema:
        - $formkit: text
          name: sina
          label: 新浪微博
          placeholder: 用于展示底部新浪微博社交信息
          help: 新浪微博主页链接
        - $formkit: text
          name: telegram
          label: Telegram
          placeholder: 用于展示底部 Telegram 社交信息
          help: Telegram 用户名
        - $formkit: text
          name: twitter
          label: Twitter
          placeholder: 用于展示底部 Twitter 社交信息
          help: Twitter 主页链接
        - $formkit: text
          name: qq
          label: 腾讯 QQ
          placeholder: 用于展示底部 QQ 社交信息
          help: QQ 号码
        - $formkit: text
          name: github
          label: Github
          placeholder: 用于展示底部 Github 社交信息
          help: GitHub 主页链接
        - $formkit: text
          name: zhihu
          label: 知乎
          placeholder: 用于展示底部知乎社交信息
          help: 知乎主页链接
        - $formkit: text
          name: mail
          label: 邮箱
          placeholder: 用于展示底部邮箱社交信息
          help: 邮箱地址
        - $formkit: radio
          name: rss
          label: 订阅按钮
          value: true
          options:
            - value: true
              label: 开启
            - value: false
              label: 关闭
    - group: other
      label: 其他
      formSchema:
        - $formkit: text
          name: Aplayer
          label: Aplayer吸底播放器
          placeholder: 网易云歌单id
          help: "网易云歌单id, 比如: 60198. 暂时就只能这样子了, 后面再优化吧"
